name: build
on:
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo Building the application...
    - name: sh
      shell: bash
      run: echo "Building..." > build.log
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo Running tests...
    - name: sh
      shell: bash
      run: echo "Running tests..." > test.log
  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: echo message
      run: echo Deploying the application...
    - name: sh
      shell: bash
      run: echo "Deploying..." > deploy.log
  Post-Build:
    if: always()
    name: Post Build
    runs-on: ubuntu-latest
    needs:
    - Build
    - Test
    - Deploy
    steps:
    - name: echo message
      run: echo Pipeline completed.
      if: always()
